## Import Modules

In [24]:
# Standard libraries
import os
import pickle
import numpy as np
from tqdm.notebook import tqdm

# ML/Deep Learning frameworks
from tensorflow import keras
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.models import Model
from keras.preprocessing.image import load_img, img_to_array


## Data directory

In [25]:
BASE = './drive/Othercomputers/My MacBook Air/imageCaptionGenerator/dataset/'

## Extract image features

In [28]:
## load vgg16 model
model = VGG16() 
## exclude last layer
model = Model(inputs=model.inputs, outputs=model.layers[-2].output) 
# print(model.summary())

## extract features from image
features = {}
directory = os.path.join(BASE, 'Images')
for i, img_name in enumerate(tqdm(os.listdir(directory))):
  if i == 3:
    break
  ## load image from file
  img_file = directory + '/' + img_name
  image = load_img(img_file, target_size=(224,224))
  ## reshape image to numpy array
  image = img_to_array(image)
  print("Display1", image)
  ## reshape data for model
  image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
  print("Display2", image)
  ## preprocess image for customized to vgg model
  image = preprocess_input(image)
  ## extract features
  feature = model.predict(image, verbose=0) # toggle off any other display
  ## get image ID
  image_id = img_name.split('.')[0] # first index after splitting image name 
  ## store features
  features[image_id] = feature

  0%|          | 0/7271 [00:00<?, ?it/s]

Display1 [[[ 72.  67.  37.]
  [ 20.  19.  14.]
  [ 33.  28.  32.]
  ...
  [  0.  10.   0.]
  [  5.  19.   6.]
  [ 11.  23.  11.]]

 [[ 68.  63.  34.]
  [ 23.  22.  17.]
  [ 37.  33.  34.]
  ...
  [  4.  16.   2.]
  [  5.  17.   3.]
  [  3.  15.   1.]]

 [[ 70.  63.  37.]
  [ 23.  22.  17.]
  [ 35.  31.  30.]
  ...
  [  9.  21.   7.]
  [ 11.  23.  11.]
  [  7.  19.   7.]]

 ...

 [[ 86.  83.  92.]
  [127. 125. 126.]
  [185. 179. 183.]
  ...
  [ 69.  66.  73.]
  [ 85.  82.  77.]
  [ 74.  69.  76.]]

 [[161. 160. 158.]
  [114. 110. 107.]
  [123. 116. 124.]
  ...
  [127. 125. 128.]
  [ 79.  75.  89.]
  [140. 138. 143.]]

 [[108. 104. 103.]
  [ 99.  93.  93.]
  [112. 107. 114.]
  ...
  [108. 106. 109.]
  [126. 123. 116.]
  [125. 122. 115.]]]
Display2 [[[[ 72.  67.  37.]
   [ 20.  19.  14.]
   [ 33.  28.  32.]
   ...
   [  0.  10.   0.]
   [  5.  19.   6.]
   [ 11.  23.  11.]]

  [[ 68.  63.  34.]
   [ 23.  22.  17.]
   [ 37.  33.  34.]
   ...
   [  4.  16.   2.]
   [  5.  17.   3.]
   [  3.